### ISSUE TITLE
Error while trying to open 

### ISSUE THREAD

**Issue by AurelienDemey** [karltechno/Reaper-Waapi-Transfer#10]
Hello

Trying to open the WAAPI Transfer window makes an error.

![image](https://user-images.githubusercontent.com/33149574/38569769-79baf02c-3cec-11e8-8345-6bc1dfd07dc2.png)

Then it makes reaper crash. So by far I've not been able to transfer anything :(

(I wish it's not something stupid, I am not even sure if I am trying to do it the right way)

Thx

**Comment by karltechno** [comment]
Hi, please try installing the Visual Studio 2017 redistributable and let me know if that fixes it: https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads - I will look into statically linking/making this more clear - thanks.

https://aka.ms/vs/15/release/vc_redist.x64.exe <- 64 bit
https://aka.ms/vs/15/release/vc_redist.x86.exe <- 32 bit

**Comment by AurelienDemey** [comment]
I tried that, but the same bug happens unfortunately

**Comment by karltechno** [comment]
Hi - I think I may have fixed your issue - please can you try using one of the dll's below and let me know if it fixes it.

Thanks

[reaper_waapi_transfer_speculative_crash_fix.zip](https://github.com/karltechno/Reaper-Waapi-Transfer/files/1899991/reaper_waapi_transfer_speculative_crash_fix.zip)

**Comment by AurelienDemey** [comment]
Still, same error again. 

(thx for answering and trying to help me though)

**Comment by karltechno** [comment]
Ok - could you let me know what version of Wwise, reaper and the extension you are using and I will see if I can repro it. Also does it happen in any project? And have you customised your reaper installation much? (if so could you send me a portable version of it?)

Fyi the above fix was an issue with parsing the wwise settings xml which could also cause a crash (I will commit a fix for that later).

Also heres the DLL's built with static CRT to rule any conflicts there out.
[reaper_waapi_transfer_staticCRT.zip](https://github.com/karltechno/Reaper-Waapi-Transfer/files/1912969/reaper_waapi_transfer_staticCRT.zip)

**Comment by nikolalkc** [comment]
I have REAPER 5.91 (x64)
Windows 10 Home (x64)
Wwise 2017.2.4.6590 and 2017.2.2.6553

Non of these fixes solved my problem.

**Comment by karltechno** [comment]
Hi, can you try this redist: https://www.dropbox.com/s/ffs6ey3zsq5vrdd/redist_msvc_141_25008.zip?dl=0
If that fails can you try again with these DLL's:
[reaper_waapi_transfer_static_040618.zip](https://github.com/karltechno/Reaper-Waapi-Transfer/files/2067941/reaper_waapi_transfer_static_040618.zip)

If neither work, can you open Reaper and create a dump when it crashes (you should be able to do this in task manager by right clicking reaper and then 'Create Dump File') and upload that.

Thanks

**Comment by nikolalkc** [comment]
Sorry, but nothing worked.

Here's a dump file. I hope I created it properly.

https://www.dropbox.com/s/sbjbjdyatemjktc/reaper.DMP?dl=0

**Comment by karltechno** [comment]
Hi @nikolalkc - thanks for taking the time to send that, I think I have found the issue. Can you try this build: 
[reaper_waapi_transfer_crash_fix.zip](https://github.com/karltechno/Reaper-Waapi-Transfer/files/2068347/reaper_waapi_transfer_crash_fix.zip)

**Comment by nikolalkc** [comment]
@karltechno Yeah, this actually works.
Thank you very much.

**Comment by karltechno** [comment]
https://github.com/karltechno/Reaper-Waapi-Transfer/commit/c2a5e24c1d7f009045f3ec381845cf8d2372a92e
