### ISSUE TITLE
Feature Request: Import settings context menu

### ISSUE THREAD

**Issue by nikolalkc** [karltechno/Reaper-Waapi-Transfer#13]
Import setting window is very useful but it's a little bit inpractical.

Easiest way to change import setting for each sound would be to have right-click context menu for each data column inside list. 

Example:

We select bunch of items in list, move mouse cursor in Import operation colum and right click one of selected rows.
Context menu pops-up with options:
```
Create New
Replace
Use Existing
```
We select one option and every selected sound is updated.
This should work the same way for each column.

**Comment by karltechno** [comment]
Hi please check the recent commit and binaries: https://github.com/karltechno/Reaper-Waapi-Transfer/releases/tag/v0.1.9-beta - I added a context menu when right clicking items in the transfer window list view which will apply those settings to selected entries.

**Comment by nikolalkc** [comment]
Yeah, this is cool now. thanks
