### ISSUE TITLE
Originals SubPath direcotry has a low character limit.

### ISSUE THREAD

**Issue by HarveyScottAudio** [karltechno/Reaper-Waapi-Transfer#15]
The Originals SubPath directory text input field appears to have an unnecessarily low character limit, which can prevent specifying even existing subdirectories. 

Does this reflect a limitation of the API?

Cheers, 

Harvey

**Comment by karltechno** [comment]
[reaper_waapi_transfer char limit fix.zip](https://github.com/karltechno/Reaper-Waapi-Transfer/files/2036649/reaper_waapi_transfer.char.limit.fix.zip)

Hi, I have attached a new build which should fix this issue. Let me know how you get on.

Cheers
