### ISSUE TITLE
Can not set the import location in wwise original folder

### ISSUE THREAD

**Issue by bear0328** [karltechno/Reaper-Waapi-Transfer#3]
sometimes we need to import different types sounds into different folder in the Original folder for wwise. can you add this feature?

**Comment by karltechno** [comment]
Sure I will take a look at this, looks like the API has functionality for it.

**Comment by karltechno** [comment]
Hi I have implemented this in the latest release. In the Import Settings window you can specify an originals sub path and set it on independent audio files. The extension will also remember the paths you have used this session so you can use the drop down to re-select recently used ones. You can see the originals sub path that is assigned to an audio file in the main screen. Hope this solves your issue and let me know if you need anything else, thanks :)

https://github.com/karltechno/Reaper-Waapi-Transfer/releases/tag/v0.1.7-beta
