### ISSUE TITLE
Option to move rather than copy rendered sounds

### ISSUE THREAD

**Issue by nikolalkc** [karltechno/Reaper-Waapi-Transfer#4]
First, I want to say thank you for this amazing tool.

Second, option to move rendered sounds would be great because REAPER won't complain when I add modified files with the same name to render queue. Now I need to delete them manually after exporting which is frustrating.

**Comment by karltechno** [comment]
Hi, I have implemented a button on the main transfer screen "Copy Files To Wwise Originals". This is enabled by default. If you disable it then after copying exported audio files to Wwise originals they will be removed from the specified REAPER export path. Hope this helps you and let me know if you have any other issues, thanks :)

https://github.com/karltechno/Reaper-Waapi-Transfer/releases/tag/v0.1.7-beta

**Comment by nikolalkc** [comment]
Thank you very much for this great option. I cannot express my gratitude.
