### ISSUE TITLE
Ctrl+A is globally hijacked by the transfer window

### ISSUE THREAD

**Issue by HarveyScottAudio** [karltechno/Reaper-Waapi-Transfer#8]
Ctrl+A is hijacked by the transfer window when open. 

Does not appear to apply to the recall window.

Repro Steps:

1. Open the Waapi Transfer Window
2. Transfer something to Wwise
3. Attempt to Ctrl+A in another application (try notepad for example)
4. Note that Waapi Transfer window still accepts Ctrl+A commands
5. Note that upon closing Transfer Window, Ctrl+A works again in other applications

**Comment by karltechno** [comment]
https://github.com/karltechno/Reaper-Waapi-Transfer/commit/ea4e2b5255678ba01d069da5c881a613b9b54f7d Fixed in this commit.
